name: Working Dirs & Shells
on: [push]
defaults:
    run:
        shell: bash
        # working-directory: /as/sa

jobs:
    display-working-directory-info:
        runs-on: ubuntu-latest

        steps:
            - name: Display Working Directory & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Changing Working Directory
              working-directory: /home/runner
              run: pwd





              

    display-working-directory-info-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh

        steps:
            - name: Display Working Directory & List Files
              run: |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
            - name: Windows Machine using Python Shell
              shell: python
              run: |
                import platform
                print(platform.processor())
